Use the arrays from the IMF and plug into luminosity function from mus_test.py. Add all luminosities maybe, plot total lumiosities

In [2]:
import numpy as np
import mus_test
import sample_IMF

https://www.cfa.harvard.edu/news/initial-mass-function

IMFs describe the probability stars are born with a given mass P(m). It’s very difficult to understand how stars of different masses are formed, but we can estimate the likelihood a star forms with a given mass using our observations of the masses of stars in the Milky Way. 

The most modern models for doing this are the Kroupa broken power law and Chabrier log-normal IMF. (These models are based solely on our observations within the Milky Way and astronomers speculate that there are different IMFs for different galaxies and are influenced by a variety of factors.)

Our goal is identify the IMFs of other galaxies by guessing IMF, generating a sample of stars from it, and them comparing the evolution of luminosities from the sample to the luminosities we get from spectroscopy.

(a) Guess IMF -> Generate sample of stars -> Generate evolution of luminosities (l1)
(b) Spectroscopy Team -> Generate evolution of luminosties (l2)
(c) Compare l1 and l2

Here is our approach:
* create random sample of stars masses (1 million solar masses)
* fix the age
* do a plot of the luminosities as a function of time
* do a sum of luminosities that come from the distributions
* compare with the table coming from spectroscopy team

### (a.1) Guess IMF

How does the script take an IMF and generate a sample of stars. What parameters from the IMF influence the distribution?
How do we define an IMF?

* m_min - minimum mass for massive stars
* m_max - maximum mass for massive stars
* alpha - power-law index
* mass_frac_in_massive_stars - fraction of mass above 8 M_sum

Other parameters
* N - number of positions (stars) in the simulation each with m_mass

Which of these other parameters do we need to keep constant?
* N should be 1 million for our purposes

In [3]:
class IMF:
    def __init__(self, m_min, m_max, alpha, mass_frac_in_massive_stars, N=1000000):
        self.m_min = m_min
        self.m_max = m_max
        self.alpha = alpha
        self.mass_frac_in_massive_stars = mass_frac_in_massive_stars
        self.N = N

m_min = 0.1
m_max = 100
alpha = -1.3
mass_frac_in_massive_stars = 0.1
N = 1000000
imf = IMF(m_min, m_max, alpha, mass_frac_in_massive_stars, N)

### (a.2) Generate sample of stars

In [20]:
star_sample = sample_IMF.do_sample_imf_distribution(imf)
print(star_sample)


    Doing a sampling with the following parameters:
    A total of 1000000 positions in the simulation, each position has a stellar mass of 10.0.
    mass fraction in massive stars (from 0.1 to 100): 0.1 (this is just a random number I made up. should depend on the exact IMF).
    power-law IMF: m_min = 0.1, m_max = 100, alpha = -1.3
    mean mass of massive stars in a sampled population: 6.123431879119229
    average number of massive stars at a position: n_average = 0.16330711596710637
    
Number of stars in each position, a total of 1000000 positions. This is a Poisson distribution with mean n_average.
[0 0 0 0 0 0 1 1 0 0]
[0 1 0 0 0 0 0 0 2 2]
[0 0 0 0 0 1 0 0 2 1]
[0 0 0 0 0 0 0 0 0 1]
[0 0 1 0 1 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0]
[0 0 0 1 0 0 0 0 1 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0]
[0 0 0 2 1 0 0 0 0 0]
[0 0 1 0 0 0 0 0 1 0]
[1 1 0 0 0 0 1 0 1 1]
[0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 1 0 0]
[0 0 0 0 2 0 1 1 0 0]
[0 0 0 1 0 0 0 0 1 0]
[0 0 1 0 0 

KeyboardInterrupt: 

In [ ]:
np.savetxt('star_masses_sample.csv', star_sample, delimiter=',', header='star_masses', comments='')

In [ ]:
print(len(star_sample))
print("First 10 stars:")
for i in range(10):
    print(star_sample[i])
print("====")
print("Max:", max(star_sample))
print("Min:", min(star_sample))
print("Mean:", np.mean(star_sample))
print("Std:", np.std(star_sample))
print("Median:", np.median(star_sample))

162721
First 10 stars:
25.645188981029403
0.11626201521727103
11.38256621652553
10.077225165038525
0.4263456099183869
3.4520225103901447
0.41497806105875634
3.4559720614471447
1.1522130452536152
1.3600328717099348
====
Max: 99.99975119507187
Min: 0.10000052626497657
Mean: 6.078422018594489
Std: 14.66169333630248
Median: 0.6760226415919991
50th Percentile: 0.6760226415919991
90th Percentile: 16.926472147079995


In [14]:
lambda_array = np.linspace(0, 10000, 1000)
flux_array = np.zeros_like(lambda_array)
filter_name = "F070W"

luminosities = mus_test.calc_luminosity(lambda_array, flux_array, filter_name)

several things affect our continuem
* bound-bound transitions - these often have small delta's. the transition between two layers is small
* bound-free transitions
* free-free transitioins - 

lines
gas-continuums
stars

Where does this process fit within the pipeline? 

What purpose does disocering about the IMF serve?

How does the IMF verify our pipeline?

In [2]:
import sample_IMF
star_masses = sample_IMF.sample_massive_stars(N=100000, m_particle=10.0)
print(star_masses)

Total numb. of stars=100000,low mass=87232, High-mass=12768, mean_low=7.3
[ 7.29211184  7.29211184  7.29211184 ...  7.29211184  7.29211184
 12.64331527]


In [ ]:
def grid_interpolator(grid, masses, ages, query_point):
    pass

In [ ]:
def get_flux():
    pass

In [ ]:
grid, masses, ages = get_flux(5, "F105W")

In [ ]:
AGE = 10
luminosities = [self.grid_interpolator(grid, masses, ages, (star_mass, AGE)) for star_mass in star_masses]
total_luminosity = sum(luminosities)